export const ar = {
  app: { name: 'منصة ذكاء الأعمال', subtitle: 'منصة لتحليل وإدارة البيانات' },
  nav: { dashboard: 'لوحة القيادة', data: 'البيانات', analytics: 'التحليلات', reports: 'التقارير', map: 'الخرائط', admin: 'الإدارة', profile: 'الملف الشخصي', logout: 'تسجيل الخروج', files: 'الملفات', sheets: 'الأوراق', settings: 'الإعدادات' },
  auth: { login: 'تسجيل الدخول', email: 'البريد الإلكتروني', password: 'كلمة المرور', loginBtn: 'دخول', forgotPassword: 'نسيت كلمة المرور؟', noAccount: 'ليس لديك حساب؟', twoFactor: 'المصادقة الثنائية', code: 'رمز التحقق', verify: 'تحقق', resetPassword: 'إعادة تعيين كلمة المرور', newPassword: 'كلمة المرور الجديدة', confirmPassword: 'تأكيد كلمة المرور' },
  dashboard: { welcome: 'مرحباً', stats: 'الإحصائيات', files: 'الملفات المستوردة', sheets: 'الأوراق', records: 'السجلات', users: 'المستخدمين', recentFiles: 'الملفات الأخيرة', recentActivity: 'النشاط الأخير', kpi: 'مؤشرات الأداء' },
  data: { import: 'استيراد', upload: 'رفع ملف', fileName: 'اسم الملف', sheetName: 'اسم الورقة', rowCount: 'الصفوف', columnCount: 'الأعمدة', type: 'النوع', created: 'تاريخ الإنشاء', actions: 'الإجراءات', search: 'بحث...', filters: 'تصفية', add: 'إضافة', edit: 'تعديل', delete: 'حذف', duplicate: 'نسخ', export: 'تصدير', importFile: 'استيراد ملف Excel/CSV/ODS', dropFile: 'أسقط الملف هنا أو انقر للاختيار', importSuccess: 'تم استيراد الملف بنجاح', confirmDelete: 'تأكيد الحذف', noData: 'لا توجد بيانات', stats: 'إحصائيات', columns: 'الأعمدة', hideColumns: 'الأعمدة المخفية' },
  analytics: { title: 'تحليل البيانات', charts: 'الرسوم البيانية', bar: 'مخطط شريطي', pie: 'مخطط دائري', line: 'مخطط خطي', area: 'مخطط مساحي', radar: 'مخطط راداري', treemap: 'خريطة شجرية', sunburst: 'مخطط شمسي', heatmap: 'خريطة حرارية', advanced: 'تحليل متقدم', groupBy: 'تجميع حسب', aggregate: 'تجميع', sum: 'المجموع', avg: 'المتوسط', count: 'العدد', timeSeries: 'سلسلة زمنية', interval: 'الفاصل الزمني' },
  map: { title: 'الخرائط', view: 'عرض الخريطة', region: 'التوزيع الجغرافي', lat: 'خط العرض', lng: 'خط الطول', label: 'العلامة', value: 'القيمة' },
  reports: { title: 'التقارير', create: 'إنشاء تقرير', name: 'اسم التقرير', type: 'النوع', generate: 'توليد', schedule: 'جدولة', lastRun: 'آخر تنفيذ', pdf: 'PDF', excel: 'Excel', word: 'Word', automatic: 'تقارير تلقائية', monthly: 'شهري', weekly: 'أسبوعي', yearly: 'سنوي', custom: 'مخصص' },
  admin: { title: 'الإدارة', users: 'المستخدمين', createUser: 'إنشاء مستخدم', editUser: 'تعديل مستخدم', firstName: 'الاسم الأول', lastName: 'الاسم الأخير', role: 'الدور', active: 'نشط', auditLogs: 'سجل التدقيق', systemStats: 'إحصائيات النظام' },
  profile: { title: 'الملف الشخصي', changePassword: 'تغيير كلمة المرور', currentPassword: 'كلمة المرور الحالية', newPassword: 'كلمة المرور الجديدة', twoFactor: 'المصادقة الثنائية', setup2FA: 'إعداد 2FA', disable2FA: 'تعطيل 2FA', enable2FA: 'تفعيل 2FA' },
  common: { save: 'حفظ', cancel: 'إلغاء', confirm: 'تأكيد', loading: 'جارٍ التحميل...', error: 'خطأ', success: 'نجاح', search: 'بحث', filter: 'تصفية', export: 'تصدير', print: 'طباعة', refresh: 'تحديث', back: 'رجوع', next: 'التالي', previous: 'السابق', page: 'صفحة', of: 'من', total: 'المجموع', all: 'الكل', none: 'لا شيء', apply: 'تطبيق', clear: 'مسح', close: 'إغلاق', delete: 'حذف', edit: 'تعديل', view: 'عرض', download: 'تحميل' },
  errors: { network: 'خطأ في الشبكة', unauthorized: 'غير مصرح', forbidden: 'وصول ممنوع', notFound: 'غير موجود', serverError: 'خطأ في الخادم', validationError: 'خطأ في التحقق' },
};
