export const en = {
  app: { name: 'BI Platform', subtitle: 'Business Intelligence Platform' },
  nav: { dashboard: 'Dashboard', data: 'Data', analytics: 'Analytics', reports: 'Reports', map: 'Mapping', admin: 'Administration', profile: 'Profile', logout: 'Logout', files: 'Files', sheets: 'Sheets', settings: 'Settings' },
  auth: { login: 'Login', email: 'Email', password: 'Password', loginBtn: 'Sign In', forgotPassword: 'Forgot password?', noAccount: 'No account?', twoFactor: 'Two-factor authentication', code: 'Verification code', verify: 'Verify', resetPassword: 'Reset password', newPassword: 'New password', confirmPassword: 'Confirm password' },
  dashboard: { welcome: 'Welcome', stats: 'Statistics', files: 'Imported files', sheets: 'Sheets', records: 'Records', users: 'Users', recentFiles: 'Recent files', recentActivity: 'Recent activity', kpi: 'Key indicators' },
  data: { import: 'Import', upload: 'Upload file', fileName: 'File name', sheetName: 'Sheet name', rowCount: 'Rows', columnCount: 'Columns', type: 'Type', created: 'Created', actions: 'Actions', search: 'Search...', filters: 'Filters', add: 'Add', edit: 'Edit', delete: 'Delete', duplicate: 'Duplicate', export: 'Export', importFile: 'Import Excel/CSV/ODS file', dropFile: 'Drop file here or click to select', importSuccess: 'File imported successfully', confirmDelete: 'Confirm deletion', noData: 'No data', stats: 'Statistics', columns: 'Columns', hideColumns: 'Hidden columns' },
  analytics: { title: 'Data Analytics', charts: 'Charts', bar: 'Bar Chart', pie: 'Pie Chart', line: 'Line Chart', area: 'Area Chart', radar: 'Radar Chart', treemap: 'Treemap', sunburst: 'Sunburst', heatmap: 'Heatmap', advanced: 'Advanced Analytics', groupBy: 'Group by', aggregate: 'Aggregation', sum: 'Sum', avg: 'Average', count: 'Count', timeSeries: 'Time Series', interval: 'Interval' },
  map: { title: 'Mapping', view: 'Map view', region: 'Region distribution', lat: 'Latitude', lng: 'Longitude', label: 'Label', value: 'Value' },
  reports: { title: 'Reports', create: 'Create report', name: 'Report name', type: 'Type', generate: 'Generate', schedule: 'Schedule', lastRun: 'Last run', pdf: 'PDF', excel: 'Excel', word: 'Word', automatic: 'Automatic reports', monthly: 'Monthly', weekly: 'Weekly', yearly: 'Yearly', custom: 'Custom' },
  admin: { title: 'Administration', users: 'Users', createUser: 'Create user', editUser: 'Edit user', firstName: 'First name', lastName: 'Last name', role: 'Role', active: 'Active', auditLogs: 'Audit logs', systemStats: 'System statistics' },
  profile: { title: 'Profile', changePassword: 'Change password', currentPassword: 'Current password', newPassword: 'New password', twoFactor: 'Two-factor authentication', setup2FA: 'Setup 2FA', disable2FA: 'Disable 2FA', enable2FA: 'Enable 2FA' },
  common: { save: 'Save', cancel: 'Cancel', confirm: 'Confirm', loading: 'Loading...', error: 'Error', success: 'Success', search: 'Search', filter: 'Filter', export: 'Export', print: 'Print', refresh: 'Refresh', back: 'Back', next: 'Next', previous: 'Previous', page: 'Page', of: 'of', total: 'Total', all: 'All', none: 'None', apply: 'Apply', clear: 'Clear', close: 'Close', delete: 'Delete', edit: 'Edit', view: 'View', download: 'Download' },
  errors: { network: 'Network error', unauthorized: 'Unauthorized', forbidden: 'Access denied', notFound: 'Not found', serverError: 'Server error', validationError: 'Validation error' },
};
