export const fr = {
  app: { name: 'BI Platform', subtitle: 'Plateforme de Business Intelligence' },
  nav: { dashboard: 'Tableau de Bord', data: 'Données', analytics: 'Analyse', reports: 'Rapports', map: 'Cartographie', admin: 'Administration', profile: 'Profil', logout: 'Déconnexion', files: 'Fichiers', sheets: 'Feuilles', settings: 'Paramètres' },
  auth: { login: 'Connexion', email: 'Email', password: 'Mot de passe', loginBtn: 'Se connecter', forgotPassword: 'Mot de passe oublié?', noAccount: 'Pas de compte?', twoFactor: 'Authentification à deux facteurs', code: 'Code de vérification', verify: 'Vérifier', resetPassword: 'Réinitialiser le mot de passe', newPassword: 'Nouveau mot de passe', confirmPassword: 'Confirmer le mot de passe' },
  dashboard: { welcome: 'Bienvenue', stats: 'Statistiques', files: 'Fichiers importés', sheets: 'Feuilles', records: 'Enregistrements', users: 'Utilisateurs', recentFiles: 'Fichiers récents', recentActivity: 'Activité récente', kpi: 'Indicateurs clés' },
  data: { import: 'Importer', upload: 'Uploader un fichier', fileName: 'Nom du fichier', sheetName: 'Nom de la feuille', rowCount: 'Lignes', columnCount: 'Colonnes', type: 'Type', created: 'Créé le', actions: 'Actions', search: 'Rechercher...', filters: 'Filtres', add: 'Ajouter', edit: 'Modifier', delete: 'Supprimer', duplicate: 'Dupliquer', export: 'Exporter', importFile: 'Importer un fichier Excel/CSV/ODS', dropFile: 'Déposer le fichier ici ou cliquer pour sélectionner', importSuccess: 'Fichier importé avec succès', confirmDelete: 'Confirmer la suppression', noData: 'Aucune donnée', stats: 'Statistiques', columns: 'Colonnes', hideColumns: 'Colonnes masquées' },
  analytics: { title: 'Analyse des données', charts: 'Graphiques', bar: 'Histogramme', pie: 'Camembert', line: 'Courbe', area: 'Aire', radar: 'Radar', treemap: 'Treemap', sunburst: 'Sunburst', heatmap: 'Heatmap', advanced: 'Analytique avancée', groupBy: 'Grouper par', aggregate: 'Agrégation', sum: 'Somme', avg: 'Moyenne', count: 'Comptage', timeSeries: 'Série temporelle', interval: 'Intervalle' },
  map: { title: 'Cartographie', view: 'Vue carte', region: 'Répartition géographique', lat: 'Latitude', lng: 'Longitude', label: 'Étiquette', value: 'Valeur' },
  reports: { title: 'Rapports', create: 'Créer un rapport', name: 'Nom du rapport', type: 'Type', generate: 'Générer', schedule: 'Planification', lastRun: 'Dernière exécution', pdf: 'PDF', excel: 'Excel', word: 'Word', automatic: 'Rapports automatiques', monthly: 'Mensuel', weekly: 'Hebdomadaire', yearly: 'Annuel', custom: 'Personnalisé' },
  admin: { title: 'Administration', users: 'Utilisateurs', createUser: 'Créer un utilisateur', editUser: 'Modifier utilisateur', firstName: 'Prénom', lastName: 'Nom', role: 'Rôle', active: 'Actif', auditLogs: "Journaux d'audit", systemStats: 'Statistiques système' },
  profile: { title: 'Profil', changePassword: 'Changer le mot de passe', currentPassword: 'Mot de passe actuel', newPassword: 'Nouveau mot de passe', twoFactor: 'Double authentification', setup2FA: 'Configurer 2FA', disable2FA: 'Désactiver 2FA', enable2FA: 'Activer 2FA' },
  common: { save: 'Enregistrer', cancel: 'Annuler', confirm: 'Confirmer', loading: 'Chargement...', error: 'Erreur', success: 'Succès', search: 'Recherche', filter: 'Filtrer', export: 'Exporter', print: 'Imprimer', refresh: 'Actualiser', back: 'Retour', next: 'Suivant', previous: 'Précédent', page: 'Page', of: 'sur', total: 'Total', all: 'Tous', none: 'Aucun', apply: 'Appliquer', clear: 'Effacer', close: 'Fermer', delete: 'Supprimer', edit: 'Modifier', view: 'Voir', download: 'Télécharger' },
  errors: { network: 'Erreur réseau', unauthorized: 'Non autorisé', forbidden: 'Accès interdit', notFound: 'Non trouvé', serverError: 'Erreur serveur', validationError: 'Erreur de validation' },
};
